#!/bin/bash
export BASEPKGS=(
 'neofetch' #necessary programs 
 'neovim'
 'xdg-user-dirs'
 'vim' 
 'thefuck'
 'python'
 'git'
 'w3m'
 'python'
 'python-pip'
 'os-prober'
 'traceroute' #network utils
 'nmap'
 'iw'
 'iwd'
 'netctl'
 'dhcpcd'
 'networkmanager'
 'grub' #grub/boot 
 'grub-customizer' 
 'efibootmgr' 
 'which' #utils
 'wget' 
 'dialog'
 'unrar' 
 'util-linux' 
 'tree' 
 'unzip' 
 'xdg-user-dirs' 
 'exfat-utils'
 'gptfdisk'
 'openssh'
 'pacman-contrib'
 'picom'
 'qemu'
 'autoconf' # build
 'automake'
 'gcc'
 'terminus-font' # fonts
)

export GUIPKGS=(
 'mesa' #xserver
 'xorg'
 'xorg-server'
 'xorg-apps'
 'xorg-drivers'
 'xorg-xkill'
 'xorg-xinit'
 'xterm'
 'lightdm' #desktop env
 'lightdm-gtk-greeter'
 'lightdm-gtk-greeter-settings'
 'dunst'
 'i3-gaps'
 'archlinux-wallpaper'
 'feh'
 'alsa-plugins' #sound
 'alsa-utils'
 'ark'
 'pulseaudio'
 'pulseaudio-alsa'
 'pulseaudio-bluetooth' #bluetooth
 'bluez-libs'
 'bluez-utils'
 'dolphin' #grapical utils
 'gparted'
 'baobab'
 'alacritty'
 'gimp' #nice to have programs
 'vlc'
 'libreoffice'
 'gwenview'
 'p7zip'
 'steam'
 'cups' #printing
 'print-manager'
 'wine-gecko' #wine
 'wine-mono'
 'winetricks'
 'lutris'
 'rofi'
 'breeze'
 'qt5ct'
 'lxappearance'
)

export AURPKGS=(
 'android-sdk-platform-tools'
 'i3-swallow-git'
 'spotify'
 'spicetify-cli'
 'flavours'
 'nerd-fonts-complete'
 'google-chrome'
 'cpupower-gui'
 'google-earth-pro'
 'polybar'
 'powder-toy'
 'ums'
 'zoom'
 'dxvk-bin'
 'mangohud'
 'i3lock-color'
)
